server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  clients:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/